### ISSUE TITLE
[Tutorial] Conference Tutorials

### ISSUE THREAD

**Issue by lmilechin** [USRSE/wg-education-training#2]
## Tutorial Selection
- [x] Review tutorial proposals
- [x] Notify authors of acceptance/rejection

## Coordinate a date
- [x] Send options for dates to authors
- [x] Send reminders (8/9)
- [x] Confirm dates with authors
- [x] Ask E&T Working Group for volunteers to run sessions
- [x] Notify US-RSE committee of dates for tutorials

## Zoom Prep
- [x] Find out how US-RSE want to run zoom sessions
- [x] Decide on Zoom registration questions (review previous questions)
- [x] Put together Zoom event/registration
- [ ] Confirm registration text with presenter?
- [x] Send links to committee
- [x] Test cloud recording

## Week of/before event prep
- [ ] Put together Zoom poll (for end of event)
- [ ] Add/remove people to #et-seminar-backchannel

## After event
- [x] Send recording to be posted with description (include relevant links to slides, papers, etc)
- [x] Send email, slack message when video is posted
- [x] Add talk to wg web page

**Comment by jarrah42** [comment]
Accepted tutorials:

1. Publish your software in conda-forge: 3.5 hours 
2. GitHub Actions for Scientific Data Workflows: 1.5 hours 
3. Using Globus Platform Services in Research Software Applications: 1.5 hours 
4. Software Quality Practices for Reproducibility: 3.5 hours 
5. Introduction to Spatial Data Processing: 3.5 hours

**Comment by jarrah42** [comment]
#4 preferred dates: 12, 11, 2, 4

**Comment by jarrah42** [comment]
#3 preferred dates: ~~2, 10, 13~~ 12, 4, 11

**Comment by lmilechin** [comment]
Previous Registration Questions:

- What is your primary role?
  - Leadership/Manager
  - Staff (RSE, Research Computing and Data professional, Library)
  - Faculty/Researcher (Tenure track, Adjunct, Research Scientist)
  - Post-Doc
  - Research Assistant Graduate Student
  - Graduate Student
  - Undergraduate
  - Other
- What is your primary area?
  - RSE (software facing)
  - Data Facing
  - Researcher Facing (facilitator)
  - Systems facing (system administrator)
  - Strategy and policy facing (leadership)
  - Student
  - Other
- What is your primary institution?
  - Primary research university R1/R2
  - Community college or similar
  - National lab
  - Non-profit
  - Government
  - Industry
  - Other
- How did you hear about this tutorial? **[Will need updating]**
  - US-RSE Newsletter or Announcement Email
  - Other Email List
  - US-RSE Slack
  - Colleague/Friend
  - Twitter
  - Other

**Comment by lmilechin** [comment]
#2 Preferred dates: **2**, 10 3
